/**
 * @fileoverview gRPC-Web generated client stub for vocab
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.15.8
// source: vocab.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.vocab = require('./vocab_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.vocab.VocabServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.vocab.VocabServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'binary';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.vocab.VocabListRequest,
 *   !proto.vocab.VocabListResponse>}
 */
const methodDescriptor_VocabService_ListVocabs = new grpc.web.MethodDescriptor(
  '/vocab.VocabService/ListVocabs',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.vocab.VocabListRequest,
  proto.vocab.VocabListResponse,
  /**
   * @param {!proto.vocab.VocabListRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.vocab.VocabListResponse.deserializeBinary
);


/**
 * @param {!proto.vocab.VocabListRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.vocab.VocabListResponse>}
 *     The XHR Node Readable Stream
 */
proto.vocab.VocabServiceClient.prototype.listVocabs =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/vocab.VocabService/ListVocabs',
      request,
      metadata || {},
      methodDescriptor_VocabService_ListVocabs);
};


/**
 * @param {!proto.vocab.VocabListRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.vocab.VocabListResponse>}
 *     The XHR Node Readable Stream
 */
proto.vocab.VocabServicePromiseClient.prototype.listVocabs =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/vocab.VocabService/ListVocabs',
      request,
      metadata || {},
      methodDescriptor_VocabService_ListVocabs);
};


module.exports = proto.vocab;

