FROM jonas27/goserver as builder

# change this line! (copies your static data into container)
COPY cmd/static static

RUN GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -o /goserver main.go

RUN useradd scratchuser && chown -R scratchuser:scratchuser /goserver

FROM alpine
COPY --from=builder /goserver /
COPY --from=builder /etc/passwd /etc/passwd
USER scratchuser
CMD ["/goserver"]