FROM jonas27/goserver as builder

# copy your data into container
COPY cmd/static static

RUN GOARCH=amd64 GOOS=linux CGO_ENABLED=0 go build -o /goserver cmd/main.go

RUN useradd scratchuser
RUN chown -R scratchuser:scratchuser /cert && chown -R scratchuser:scratchuser /static

FROM alpine
COPY --from=builder /goserver /
COPY --from=builder /etc/passwd /etc/passwd
USER scratchuser
CMD ["/goserver"]